version: 2
jobs:
  build: 
        machine:
            enabled: true       
        steps:
            - checkout:
            - attach_workspace:
                at: ~/
            - run:
                name: Upgrade Lein
                command: echo y | sudo LEIN_ROOT=1 lein upgrade
            - run:
                name: Install postgres client
                command: sudo apt-get update && sudo apt-get install -y postgresql-client
            - run:
                name: Start the world
                command: |
                      bin/big_ole_test.sh
