version: 2
jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: circleci/python:2.7.14
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install and login AWS configuration
          command: |
             sudo pip install awscli
             python env_var.py
             docker create -v /root/.docker/ --name configs ubuntu
             docker cp env_var.txt configs:env_var.txt
               
workflows:
  version: 2
  test:
      jobs:
          - test:
              context: colliectl
