version: 2
jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: circleci/python:2.7.14
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker

               
workflows:
  version: 2
  test:
      jobs:
          - test:
              context: colliectl
